#%RAML 1.0
title: exp-user-api

types:
  user: !include exchange_modules/a4d36569-50db-4c84-9236-85487d0e3d4f/fragment-user/1.0.1/fragment-user.raml
  collection-users: !include datatypes/collection-users.raml
mediaType: application/json

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication

securedBy:
  - basic

/getUser/{username}:
  get:
    description: Get Users by username
    responses:
      200:
        body:
          application/json:
              type: user

/getUsers:
  get:
    description: Get Users from specific query parameters
    queryParameters:
      active:
        type: boolean
        required: false
      fullName:
        type: string
        minLength: 5
        maxLength: 100
        required: false
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: collection-users

/createUser:
  post:
    description: Create User
    body:
      application/json:
        type: user

/createUsers:
  post:
    description: Create Users
    body:
      application/json:
        type: collection-users
          
/delete/{username}:
  delete:
    description: Delete User by username

/update/{username}:
  put:
    description: Update User by username
    body:
      application/json:
        type: user